version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/transitaz
    ports:
      - 8000:8000
    image: app:transitaz
    container_name: django_container
    command:
      - python manage.py runserver 0.0.0.0.8000
    depends_on:
      - db
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: 'transitaz'
      MYSQL_ALLOWED_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql




