version: "3.9"

services:
  db:
    image: mysql
    env_file:
      - .env
    volumes:
      - transitaz_db:/var/lib/mysql
    ports:
      - "3307:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/transitaz/
    depends_on:
      - db
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
volumes:
  transitaz_db: