# Generated by Django 3.2.9 on 2021-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether user verified his account through the link he received in email that backend sends after sign up'),
        ),
    ]
