# Generated by Django 3.2.9 on 2021-11-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'busses'},
        ),
        migrations.AddField(
            model_name='busstation',
            name='coords',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
