# Generated by Django 3.2.9 on 2021-11-21 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.busstation')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
