# Generated by Django 3.2.9 on 2021-11-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='stations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.busstation'),
        ),
    ]
