# Generated by Django 3.2.9 on 2021-11-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_city_stations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='stations',
        ),
        migrations.AddField(
            model_name='busstation',
            name='stations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.city'),
        ),
    ]
