# Generated by Django 3.2.9 on 2021-11-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20211121_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstation',
            old_name='stations',
            new_name='city',
        ),
    ]
