# Generated by Django 3.2.9 on 2021-11-24 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0006_auto_20211123_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('capacity', models.IntegerField()),
                ('ticket_price', models.FloatField()),
                ('departures_at', models.DateTimeField()),
                ('arrives_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='busstation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_stations', to='ticket.city'),
        ),
        migrations.AlterField(
            model_name='busticket',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_tickets', to='ticket.bus'),
        ),
        migrations.AlterField(
            model_name='busticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrainTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_tickets', to=settings.AUTH_USER_MODEL)),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_tickets', to='ticket.train')),
            ],
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('region', models.CharField(max_length=50)),
                ('coords', models.CharField(blank=True, max_length=100, null=True)),
                ('map_x', models.FloatField(blank=True, null=True)),
                ('map_y', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_stations', to='ticket.city')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_come', to='ticket.trainstation'),
        ),
        migrations.AddField(
            model_name='train',
            name='starting_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_start', to='ticket.trainstation'),
        ),
    ]
