# Generated by Django 3.2.9 on 2021-12-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20211202_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busticket',
            options={'ordering': ('-purchased_at',)},
        ),
        migrations.AlterModelOptions(
            name='trainticket',
            options={'ordering': ('-purchased_at',)},
        ),
    ]
