# Generated by Django 3.2.9 on 2021-12-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20211204_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='arrives_at',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='train',
            name='arrives_at',
        ),
        migrations.AddField(
            model_name='bus',
            name='child_price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='has_seats_for_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='student_price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='type',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train')], default='Bus', max_length=10),
        ),
        migrations.AddField(
            model_name='bus',
            name='units',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='busstation',
            name='type',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train')], default='Bus', max_length=10),
        ),
        migrations.AddField(
            model_name='busticket',
            name='seat',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='busticket',
            name='type',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Student', 'Student'), ('Child', 'Child')], default='Adult', max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departures_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
