# Generated by Django 3.2.9 on 2021-12-07 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0010_auto_20211207_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train')], default='Bus', max_length=10)),
                ('description', models.CharField(max_length=2000)),
                ('region', models.CharField(max_length=50)),
                ('coords', models.CharField(max_length=100)),
                ('map_x', models.FloatField(blank=True, null=True)),
                ('map_y', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='ticket.city')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Adult', 'Adult'), ('Student', 'Student'), ('Child', 'Child')], default='Adult', max_length=100)),
                ('seat', models.IntegerField(default=1)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-purchased_at',),
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('type', models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train')], default='Bus', max_length=10)),
                ('capacity', models.IntegerField()),
                ('units', models.IntegerField(default=1)),
                ('price', models.FloatField(default=1)),
                ('child_price', models.FloatField(default=1)),
                ('student_price', models.FloatField(default=1)),
                ('departures_at', models.DateTimeField(blank=True, null=True)),
                ('has_seats_for_disabled', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive', to='ticket.station')),
                ('starting_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='ticket.station')),
            ],
            options={
                'verbose_name_plural': 'busses',
            },
        ),
        migrations.RemoveField(
            model_name='busstation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='busticket',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='busticket',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='BusStation',
        ),
        migrations.DeleteModel(
            name='BusTicket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.transport'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
