# Generated by Django 3.2.9 on 2021-12-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_alter_station_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainstation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='train',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.DeleteModel(
            name='TrainStation',
        ),
        migrations.DeleteModel(
            name='TrainTicket',
        ),
    ]
