# Generated by Django 3.2.9 on 2021-12-07 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0013_auto_20211207_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={},
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='child_price',
            new_name='business_price',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='student_price',
            new_name='low_cost_price',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
