# Generated by Django 3.2.9 on 2021-12-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_transport_arrives_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Usual', 'Usual'), ('Lowcost', 'Lowcost'), ('Business', 'Business')], default='Adult', max_length=100),
        ),
    ]
