# Generated by Django 3.2.9 on 2021-12-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20211208_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='bus',
            new_name='transport',
        ),
    ]
