# Generated by Django 3.2.9 on 2021-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_rename_bus_ticket_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transport',
            name='has_air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transport',
            name='has_free_snacks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transport',
            name='has_multimedia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transport',
            name='has_sockets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transport',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Standart', 'Standart'), ('Ekonom', 'Ekonom'), ('Biznes', 'Biznes')], default='Standart', max_length=100),
        ),
    ]
