# Generated by Django 3.2.9 on 2021-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_auto_20211217_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='map_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='station',
            name='map_y',
            field=models.FloatField(default=0),
        ),
    ]
